
[functions.upload-to-cloudinary]
enabled = true
verify_jwt = true
import_map = "./functions/upload-to-cloudinary/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload-to-cloudinary/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload-to-cloudinary/*.html" ]

[functions.delete-cloudinary-images]
enabled = true
verify_jwt = true
import_map = "./functions/delete-cloudinary-images/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-cloudinary-images/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-cloudinary-images/*.html" ]
